### ISSUE TITLE
Problem with Dotfuscator

### ISSUE THREAD

**Issue by Mario-HL-Duarte** [xamarin/XamarinAndroidXMigration#12]
I couldn't compile my project using Dotfuscator:

> Symbols were found but are not matching the assembly
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(String source, String destination) in D:\a\1\s\source\Xamarin.AndroidX.Migration\CecilMigrator.cs:line 85
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(IEnumerable`1 assemblies) in D:\a\1\s\source\Xamarin.AndroidX.Migration\CecilMigrator.cs:line 50
   at Xamarin.AndroidX.Migration.BuildTasks.CecilfyFiles.Execute() in D:\a\1\s\source\Xamarin.AndroidX.Migration.BuildTasks\CecilfyFiles.cs:line 35	x2Apps.CheckPlaca.App.Android	C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview02\build\Xamarin.AndroidX.Migration.targets	182	

Setting the DotfuscatorXamarinEnabled option to FALSE in my csproj solves the problem.

**Comment by tranb3r** [comment]
Same for me, using Babel instead of Dotfuscator

**Comment by tranb3r** [comment]
I've moved my obfuscation task after _AndroidXCecilfy and now I can build and manually deploy my app (but deploy from VS still fails though).
