### ISSUE TITLE
AndroidX Migration Fails with The Method or operation is not implemented

### ISSUE THREAD

**Issue by inforithmics** [xamarin/XamarinAndroidXMigration#27]
Visual Studio 2019 16.4

Callstack of the exception

The method or operation is not implemented.
   at Mono.Cecil.Pdb.NativePdbWriterProvider.GetSymbolWriter(ModuleDefinition module, Stream symbolStream)
   at Mono.Cecil.Pdb.PdbWriterProvider.GetSymbolWriter(ModuleDefinition module, Stream symbolStream)
   at Mono.Cecil.ModuleWriter.GetSymbolWriter(ModuleDefinition module, String fq_name, ISymbolWriterProvider symbol_writer_provider, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(String source, String destination) in D:\a\1\s\source\Xamarin.AndroidX.Migration\Migration\CecilMigrator.cs:line 117
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(IEnumerable`1 assemblies) in D:\a\1\s\source\Xamarin.AndroidX.Migration\Migration\CecilMigrator.cs:line 50
   at Xamarin.AndroidX.Migration.BuildTasks.CecilfyFiles.Execute() in D:\a\1\s\source\Xamarin.AndroidX.Migration\BuildTasks\CecilfyFiles.cs:line 35	Muellerchur.Xamos.Mobile.Android	

I attached a debugger and disassembled the method.

And the method has this Implementation.
```
public ISymbolWriter GetSymbolWriter(ModuleDefinition module, Stream symbolStream)
    {
      throw new NotImplementedException();
    }		
```
So it isn't implemented.

**Comment by inforithmics** [comment]
I analysed it further and have now a reproduction project
[App16.zip](https://github.com/xamarin/XamarinAndroidXMigration/files/3923737/App16.zip)

Open it and compile it in release Mode.
The reason why this crash happens is that I reference a third party nuget (Acr.UserDialog) which has pdb files that are not portable.
Then ConvertDebuggingFiles creates an mdb File for Debugging.

https://github.com/xamarin/Xamarin.Forms/pull/4201

But Cecil cannot write this pdb/mdb and crashes.
So knowing this the solution is to simply delete the pdb and mdb file from the nuget folder of acr.userdialog and it works.

A better longterm solution would be that the Component creates a portable pdb.

**Comment by leonluc-dev** [comment]
It seems this might be related to this issue in the AndroidX repository: https://github.com/xamarin/AndroidX/issues/11

It was fixed recently, hopefully that fix makes it to nuget soon.
