### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by zetanet** [xamarin/XamarinAndroidXMigration#30]
Hi,
I have a Xamarin Android application targetting framework Android 10.0 (Q) that use the following packages..

Xamarin.Android.Support.v4 28.0.0.3
Xamarin.Android.Support.v7.AppCompat 28.0.0.3
Xamarin.Android.Support.v7.CardView 28.0.0.3
Xamarin.Android.Support.v7.Preference 28.0.0.3
Xamarin.Android.Support.v7.RecyclerView 28.0.0.3
Xamarin.Android.Support.Vector.Drawable 28.0.0.3
Xamarin.Android.Support.VersionedParcelable 28.0.0.3
Xamarin.Android.Support.ViewPager 28.0.0.3

..and this packages for enable Google FCM messaging..

Xamarin.GooglePlayServices.Base 71.1610.0
Xamarin.GooglePlayServices.Basement 71.1620.0
Xamarin.GooglePlayServices.Stats 71.1601.0
Xamarin.GooglePlayServices.Tasks 71.1601.0

Xamarin.Firebase.Common 71.1610.0
Xamarin.Firebase.Iid 71.1710.0
Xamarin.Firebase.Iid.Interop 71.1601.0
Xamarin.Firebase.Measurement.Connector 71.1701.0
Xamarin.Firebase.Messaging 71.1740.0

...After adding Xamarin.AndroidX.Migration 1.0.0-preview06 package and added missing Xamarin.AndroidX.* packages…

Xamarin.AndroidX.Activity 1.0.0-preview06
Xamarin.AndroidX.Annotation 1.1.0-preview06
Xamarin.AndroidX.AppCompat 1.1.0-preview06
Xamarin.AndroidX.AppCompat.Resources 1.1.0-preview06
Xamarin.AndroidX.Arch.Core.Common 2.1.0-preview06
Xamarin.AndroidX.Arch.Core.Runtime 2.1.0-preview06
Xamarin.AndroidX.AsyncLayoutInflater 1.0.0-preview06
Xamarin.AndroidX.Browser 1.1.0-preview06
Xamarin.AndroidX.CardView 1.0.0-preview06
Xamarin.AndroidX.Collection 1.1.0-preview06
Xamarin.AndroidX.CoordinatorLayout 1.0.0-preview06
Xamarin.AndroidX.Core 1.1.0-preview06
Xamarin.AndroidX.CursorAdapter 1.0.0-preview06
Xamarin.AndroidX.CustomView 1.0.0-preview06
Xamarin.AndroidX.DocumentFile 1.0.1-preview06
Xamarin.AndroidX.DrawerLayout 1.0.0-preview06
Xamarin.AndroidX.Fragment 1.1.0-preview06
Xamarin.AndroidX.Interpolator 1.0.0-preview06
Xamarin.AndroidX.Legacy.Support.Core.UI 1.0.0-preview06
Xamarin.AndroidX.Legacy.Support.Core.Utils 1.0.0-preview06
Xamarin.AndroidX.Legacy.Support.V4 1.0.0-preview06
Xamarin.AndroidX.Lifecycle.Common 2.1.0-preview06
Xamarin.AndroidX.Lifecycle.LiveData 2.1.0-preview06
Xamarin.AndroidX.Lifecycle.LiveData.Core 2.1.0-preview06
Xamarin.AndroidX.Lifecycle.Runtime 2.1.0-preview06
Xamarin.AndroidX.Lifecycle.ViewModel 2.1.0-preview06
Xamarin.AndroidX.Loader 1.1.0-preview06
Xamarin.AndroidX.LocalBroadcastManager 1.0.0-preview06
Xamarin.AndroidX.Media 1.1.0-preview06
Xamarin.AndroidX.MultiDex 2.0.1-preview06
Xamarin.AndroidX.Preference 1.1.0-preview06
Xamarin.AndroidX.Print 1.0.0-preview06
Xamarin.AndroidX.RecyclerView 1.0.0-preview06
Xamarin.AndroidX.SavedState 1.0.0-preview06
Xamarin.AndroidX.SlidingPaneLayout 1.1.0-preview06
Xamarin.AndroidX.SwipeRefreshLayout 1.0.0-preview06
Xamarin.AndroidX.Transition 1.2.0-preview06
Xamarin.AndroidX.VectorDrawable 1.1.0-preview06
Xamarin.AndroidX.VectorDrawable.Animated 1.1.0-preview06
Xamarin.AndroidX.VersionedParcelable 1.1.0-preview06
Xamarin.AndroidX.ViewPager 1.0.0-preview06

..the Build process show the follwing error…

**1>------ Build started: Project: ZetaHouseMobileApp, Configuration: Debug Any CPU ------
1>  ZetaHouseMobileApp -> C:\GitHub\HelloAndroid\HelloAndroidApp\HelloAndroidApp\bin\Debug\ZetaHouseMobileApp.dll
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/ItemListIntents;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/NoteIntents;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/ReserveIntents;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/SearchIntents;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/AccountPicker;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/BlockingServiceConnection;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ConnectionResult;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/Feature;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/FirstPartyScopes;
1>  
1>  UNEXPECTED TOP-LEVEL EXCEPTION:
1>  java.lang.RuntimeException: Translation has been interrupted
1>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:614)
1>  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:310)
1>  	at com.android.dx.command.dexer.Main.runDx(Main.java:288)
1>  	at com.android.dx.command.dexer.Main.main(Main.java:244)
1>  	at com.android.dx.command.Main.main(Main.java:95)
1>  Caused by: java.lang.InterruptedException: Too many errors
1>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:606)
1>  	... 4 more
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2613,3): error : java.lang.IllegalArgumentException: already added :  Lcom/google/android/gms/actions/ItemListIntents;
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========**

I dont undestand where is the problem in migration process to AndroidX.

I've just tried to uninstall all Xamarin.Firebase.* and Xamarin.GooglePlayServices.* packages , then readded but problem persists..

Thanks for any suggestions.
Best Regards.

**Comment by zetanet** [comment]
****** Update 20/12/2019
 The default dependency for package Xamarin.AndroidX.Migration is Xamarin.AndroidX.MultiDex (>= 2.0.1-preview03)

After upgrading to Xamarin.AndroidX.MultiDex (2.0.1-preview06) the building error was changed..

**2>  C:\GitHub\HelloAndroid\HelloAndroidApp\HelloAndroidApp\obj\Debug\100\lp\52\jl\res\values\values.xml(35): error APT1000: Attribute "imageAspectRatioAdjust" already defined with incompatible format.
2>  C:\GitHub\HelloAndroid\HelloAndroidApp\HelloAndroidApp\obj\Debug\100\lp\95\jl\res\values\values.xml(36): error APT1000: Original attribute defined here.
2>  C:\GitHub\HelloAndroid\HelloAndroidApp\HelloAndroidApp\obj\Debug\100\lp\52\jl\res\values\values.xml(48): error APT1000: Attribute "buttonSize" already defined with incompatible format.
2>  C:\GitHub\HelloAndroid\HelloAndroidApp\HelloAndroidApp\obj\Debug\100\lp\95\jl\res\values\values.xml(49): error APT1000: Original attribute defined here.
2>  C:\GitHub\HelloAndroid\HelloAndroidApp\HelloAndroidApp\obj\Debug\100\lp\52\jl\res\values\values.xml(56): error APT1000: Attribute "colorScheme" already defined with incompatible format.
2>  C:\GitHub\HelloAndroid\HelloAndroidApp\HelloAndroidApp\obj\Debug\100\lp\95\jl\res\values\values.xml(57): error APT1000: Original attribute defined here.**

Googling i was reading the error was related to the Xamarin.GooglePlayServices.Base nuget package..

Now the situation ..

I have i branch before migration that complile without any problem…
The branch after migration compile with error above…

I provide verbose build log for investigation..

:(

[Xamarin.GooglePlayServices.Base_Compile_After_Migration.txt](https://github.com/xamarin/XamarinAndroidXMigration/files/3988716/Xamarin.GooglePlayServices.Base_Compile_After_Migration.txt)
[Xamarin.GooglePlayServices.Base_Compile_BeforeMigration.txt](https://github.com/xamarin/XamarinAndroidXMigration/files/3988717/Xamarin.GooglePlayServices.Base_Compile_BeforeMigration.txt)
