### ISSUE TITLE
Source assembly does not exist: at Xamarin.AndroidX.Migration.CecilMigrator.Migrate

### ISSUE THREAD

**Issue by kgbuddhima** [xamarin/XamarinAndroidXMigration#38]
I have migrated my Xamarin android app using VS 2019 Community  v 15.4

It worked fine in debug mode.

But when I ran it in Release mode, it failed with following error.

Here are my configurations 
Target version : Android Q
Compile using : Android Q
Min version : Lollipop

> Source assembly does not exist: 'MyApp.Android.dll'.
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(String source, String destination) in D:\a\1\s\source\Xamarin.AndroidX.Migration\Migration\CecilMigrator.cs:line 66
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(IEnumerable`1 assemblies) in D:\a\1\s\source\Xamarin.AndroidX.Migration\Migration\CecilMigrator.cs:line 50
   at Xamarin.AndroidX.Migration.BuildTasks.CecilfyFiles.Execute() in D:\a\1\s\source\Xamarin.AndroidX.Migration\BuildTasks\CecilfyFiles.cs:line 35	MyApp.Android

**Comment by kgbuddhima** [comment]
Then I set the Linking to "None" the project built without errors. seems there is a linking issue with Android X
